apiVersion: v1
kind: Pod
metadata: 
  name: progres-pod
  labels:
    name: progres-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTRES_USER
          value: "postgres"
        - name: POSTRES_PASSWORD
          value: "postgres"