apiVersion: v1
kind: Service
metadata:
  name: postgres-pod
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5342
  selector:
    name: postgres-pod
    app: demo-voting-app